export const NILAI_AKADEMIK_CATEGORIES = [
  'numerik',
  'bahasa',
  'sains',
  'sosial',
  'teknologi',
  'agama',
  'kreativitas',
  'softskill',
] as const;

export type AcademicCategory = typeof NILAI_AKADEMIK_CATEGORIES[number];

export const DEFAULT_SEMESTER_WEIGHTS: Record<number, number> = {
  1: 0.10,
  2: 0.15,
  3: 0.20,
  4: 0.25,
  5: 0.30,
};

export const IDENTITY_HEADER_KEYS = new Set([
  'no',
  'nomor',
  'nisn',
  'nis',
  'nama',
  'nama siswa',
  'jk',
  'jenis kelamin',
  'kelas',
  'jurusan',
  'program keahlian',
  'kompetensi keahlian',
  'asal sekolah',
  'sekolah',
]);

export const IGNORED_SUBJECT_KEYS = new Set([
  'dll',
  'dan lain lain',
  'lainnya',
  'keterangan',
  'catatan',
  'rata rata',
  'rata-rata',
  'jumlah',
  'total',
]);

export const EXACT_SUBJECT_CATEGORY_MAP: Record<string, AcademicCategory> = {
  // Numerik
  'matematika': 'numerik',
  'matematika wajib': 'numerik',
  'matematika peminatan': 'numerik',
  'matematika lanjutan': 'numerik',
  'statistika': 'numerik',
  'statistik': 'numerik',
  'kalkulus': 'numerik',
  'logika matematika': 'numerik',
  'akuntansi': 'numerik',
  'keuangan': 'numerik',
  'administrasi keuangan': 'numerik',

  // Bahasa
  'bahasa indonesia': 'bahasa',
  'b indonesia': 'bahasa',
  'b indo': 'bahasa',
  'indonesia': 'bahasa',
  'bahasa inggris': 'bahasa',
  'b inggris': 'bahasa',
  'inggris': 'bahasa',
  'bahasa arab': 'bahasa',
  'b arab': 'bahasa',
  'arab': 'bahasa',
  'bahasa jawa': 'bahasa',
  'bahasa sunda': 'bahasa',
  'bahasa jepang': 'bahasa',
  'bahasa mandarin': 'bahasa',
  'bahasa jerman': 'bahasa',
  'bahasa perancis': 'bahasa',
  'sastra indonesia': 'bahasa',
  'sastra inggris': 'bahasa',
  'literasi': 'bahasa',

  // Sains
  'ipa': 'sains',
  'ilmu pengetahuan alam': 'sains',
  'fisika': 'sains',
  'kimia': 'sains',
  'biologi': 'sains',
  'science': 'sains',
  'projek ipa': 'sains',
  'laboratorium': 'sains',
  'anatomi': 'sains',
  'farmakologi': 'sains',
  'dasar dasar kesehatan': 'sains',
  'dasar kesehatan': 'sains',
  'dasar agribisnis': 'sains',
  'agroteknologi': 'sains',
  'geologi': 'sains',
  'astronomi': 'sains',

  // Sosial
  'ips': 'sosial',
  'ilmu pengetahuan sosial': 'sosial',
  'sejarah': 'sosial',
  'sejarah indonesia': 'sosial',
  'sejarah peminatan': 'sosial',
  'ekonomi': 'sosial',
  'sosiologi': 'sosial',
  'geografi': 'sosial',
  'antropologi': 'sosial',
  'ppkn': 'sosial',
  'pkn': 'sosial',
  'pendidikan pancasila': 'sosial',
  'pendidikan kewarganegaraan': 'sosial',
  'kewarganegaraan': 'sosial',
  'administrasi umum': 'sosial',
  'administrasi perkantoran': 'sosial',
  'layanan dasar': 'sosial',

  // Teknologi
  'informatika': 'teknologi',
  'tik': 'teknologi',
  'teknologi informasi dan komunikasi': 'teknologi',
  'komputer': 'teknologi',
  'pemrograman': 'teknologi',
  'pemrograman dasar': 'teknologi',
  'pemrograman web': 'teknologi',
  'basis data': 'teknologi',
  'database': 'teknologi',
  'jaringan komputer': 'teknologi',
  'sistem komputer': 'teknologi',
  'simulasi digital': 'teknologi',
  'rpl': 'teknologi',
  'rekayasa perangkat lunak': 'teknologi',
  'tkj': 'teknologi',
  'teknik komputer dan jaringan': 'teknologi',
  'iot': 'teknologi',
  'robotika': 'teknologi',
  'elektronika': 'teknologi',
  'dasar listrik dan elektronika': 'teknologi',
  'teknik mesin': 'teknologi',
  'teknik otomotif': 'teknologi',
  'gambar teknik': 'teknologi',

  // Agama
  'pendidikan agama': 'agama',
  'pendidikan agama islam': 'agama',
  'pai': 'agama',
  'agama islam': 'agama',
  'pendidikan agama kristen': 'agama',
  'pendidikan agama katolik': 'agama',
  'pendidikan agama hindu': 'agama',
  'pendidikan agama buddha': 'agama',
  'pendidikan agama konghucu': 'agama',
  'aqidah akhlak': 'agama',
  'akidah akhlak': 'agama',
  'fikih': 'agama',
  'fiqih': 'agama',
  'alquran hadis': 'agama',
  'al quran hadis': 'agama',
  'quran hadis': 'agama',
  'sejarah kebudayaan islam': 'agama',
  'ski': 'agama',
  'tahfidz': 'agama',
  'tafsir': 'agama',
  'hadis': 'agama',
  'bahasa arab agama': 'agama',

  // Kreativitas
  'seni budaya': 'kreativitas',
  'seni rupa': 'kreativitas',
  'seni musik': 'kreativitas',
  'seni tari': 'kreativitas',
  'seni teater': 'kreativitas',
  'prakarya': 'kreativitas',
  'prakarya dan kewirausahaan': 'kreativitas',
  'pkk': 'kreativitas',
  'produk kreatif dan kewirausahaan': 'kreativitas',
  'desain': 'kreativitas',
  'desain grafis': 'kreativitas',
  'desain komunikasi visual': 'kreativitas',
  'dkv': 'kreativitas',
  'multimedia': 'kreativitas',
  'animasi': 'kreativitas',
  'fotografi': 'kreativitas',
  'videografi': 'kreativitas',
  'produksi audio visual': 'kreativitas',

  // Softskill
  'pjok': 'softskill',
  'pendidikan jasmani olahraga dan kesehatan': 'softskill',
  'penjas': 'softskill',
  'bimbingan konseling': 'softskill',
  'bk': 'softskill',
  'projek penguatan profil pelajar pancasila': 'softskill',
  'p5': 'softskill',
  'pengembangan diri': 'softskill',
  'etika profesi': 'softskill',
  'komunikasi': 'softskill',
  'public speaking': 'softskill',
  'kewirausahaan': 'softskill',
  'entrepreneurship': 'softskill',
  'manajemen organisasi': 'softskill',
};

export const KEYWORD_SUBJECT_CATEGORY_RULES: Array<{
  category: AcademicCategory;
  keywords: string[];
}> = [
  { category: 'agama', keywords: ['agama', 'islam', 'kristen', 'katolik', 'hindu', 'buddha', 'konghucu', 'akidah', 'aqidah', 'akhlak', 'fikih', 'fiqih', 'quran', 'hadis', 'tahfidz', 'tafsir', 'syariah', 'ski'] },
  { category: 'teknologi', keywords: ['informatika', 'tik', 'komputer', 'pemrograman', 'programming', 'software', 'web', 'aplikasi', 'database', 'basis data', 'jaringan', 'rpl', 'tkj', 'iot', 'robot', 'elektronik', 'listrik', 'mesin', 'otomotif', 'teknik', 'gambar teknik'] },
  { category: 'bahasa', keywords: ['bahasa', 'sastra', 'literasi', 'indonesia', 'inggris', 'arab', 'jepang', 'mandarin', 'jerman', 'perancis', 'jawa', 'sunda'] },
  { category: 'numerik', keywords: ['matematika', 'statistik', 'statistika', 'kalkulus', 'aljabar', 'akuntansi', 'keuangan', 'pajak'] },
  { category: 'sains', keywords: ['ipa', 'fisika', 'kimia', 'biologi', 'science', 'laboratorium', 'kesehatan', 'farmasi', 'gizi', 'agribisnis', 'agro', 'geologi', 'astronomi', 'keperawatan'] },
  { category: 'sosial', keywords: ['ips', 'sejarah', 'ekonomi', 'sosiologi', 'geografi', 'antropologi', 'pancasila', 'ppkn', 'pkn', 'kewarganegaraan', 'administrasi', 'hukum', 'politik'] },
  { category: 'kreativitas', keywords: ['seni', 'budaya', 'prakarya', 'kreatif', 'desain', 'dkv', 'multimedia', 'animasi', 'foto', 'video', 'audio', 'musik', 'tari', 'teater', 'rupa'] },
  { category: 'softskill', keywords: ['pjok', 'jasmani', 'olahraga', 'kesehatan', 'bk', 'bimbingan', 'konseling', 'p5', 'profil pelajar', 'pengembangan diri', 'etika', 'komunikasi', 'public speaking', 'kewirausahaan', 'organisasi'] },
];
