-- SkillLens controlled seed: master tag digeneralkan agar pilihan mirip masuk domain SPK yang sama.
-- Aman dijalankan berulang karena memakai ON DUPLICATE KEY UPDATE.

INSERT INTO master_tags (tipe, label, mapped_key, kategori_hint, sort_order, is_active) VALUES
('minat','Pemrograman','teknologi_software','teknologi',1,1),
('minat','Website','teknologi_software','teknologi',2,1),
('minat','Aplikasi Mobile','teknologi_software','teknologi',3,1),
('minat','Teknologi Informasi','teknologi_software','teknologi',4,1),
('minat','Sistem Informasi','teknologi_software','teknologi',5,1),
('minat','Artificial Intelligence','teknologi_software','teknologi',6,1),
('minat','Cyber Security','teknologi_software','teknologi',7,1),
('minat','Data','data_analitik','data',8,1),
('minat','Statistika','data_analitik','data',9,1),
('minat','Analisis Data','data_analitik','data',10,1),
('minat','Excel','data_analitik','data',11,1),
('minat','Database','data_analitik','data',12,1),
('minat','Matematika Terapan','data_analitik','data',13,1),
('minat','Desain Grafis','desain_kreatif','kreatif',14,1),
('minat','UI/UX','desain_kreatif','kreatif',15,1),
('minat','Figma','desain_kreatif','kreatif',16,1),
('minat','Canva','desain_kreatif','kreatif',17,1),
('minat','Fotografi','desain_kreatif','kreatif',18,1),
('minat','Videografi','desain_kreatif','kreatif',19,1),
('minat','Animasi','desain_kreatif','kreatif',20,1),
('minat','Branding','desain_kreatif','kreatif',21,1),
('minat','Bisnis','bisnis_marketing','bisnis',22,1),
('minat','Wirausaha','bisnis_marketing','bisnis',23,1),
('minat','Jualan Online','bisnis_marketing','bisnis',24,1),
('minat','Digital Marketing','bisnis_marketing','bisnis',25,1),
('minat','Manajemen','bisnis_marketing','bisnis',26,1),
('minat','Ekonomi','bisnis_marketing','bisnis',27,1),
('minat','Startup','bisnis_marketing','bisnis',28,1),
('minat','Akuntansi','keuangan_administrasi','keuangan',29,1),
('minat','Keuangan','keuangan_administrasi','keuangan',30,1),
('minat','Administrasi','keuangan_administrasi','keuangan',31,1),
('minat','Perbankan','keuangan_administrasi','keuangan',32,1),
('minat','Pajak','keuangan_administrasi','keuangan',33,1),
('minat','Kesehatan','kesehatan_sains','kesehatan',34,1),
('minat','Biologi','kesehatan_sains','kesehatan',35,1),
('minat','Kimia','kesehatan_sains','kesehatan',36,1),
('minat','Farmasi','kesehatan_sains','kesehatan',37,1),
('minat','Gizi','kesehatan_sains','kesehatan',38,1),
('minat','Keperawatan','kesehatan_sains','kesehatan',39,1),
('minat','Laboratorium','kesehatan_sains','kesehatan',40,1),
('minat','Mengajar','pendidikan_sosial','sosial',41,1),
('minat','Psikologi','pendidikan_sosial','sosial',42,1),
('minat','Konseling','pendidikan_sosial','sosial',43,1),
('minat','Organisasi Sosial','pendidikan_sosial','sosial',44,1),
('minat','Relawan','pendidikan_sosial','sosial',45,1),
('minat','Public Speaking','komunikasi_media','komunikasi',46,1),
('minat','Menulis','komunikasi_media','komunikasi',47,1),
('minat','Jurnalistik','komunikasi_media','komunikasi',48,1),
('minat','Bahasa','komunikasi_media','komunikasi',49,1),
('minat','Humas','komunikasi_media','komunikasi',50,1),
('minat','Konten Kreator','komunikasi_media','komunikasi',51,1),
('minat','Elektronika','teknik_rekayasa','teknik',52,1),
('minat','Listrik','teknik_rekayasa','teknik',53,1),
('minat','Otomotif','teknik_rekayasa','teknik',54,1),
('minat','Robotik','teknik_rekayasa','teknik',55,1),
('minat','IoT','teknik_rekayasa','teknik',56,1),
('minat','Mekanik','teknik_rekayasa','teknik',57,1),
('minat','Pertanian','agro_lingkungan','agro',58,1),
('minat','Peternakan','agro_lingkungan','agro',59,1),
('minat','Perikanan','agro_lingkungan','agro',60,1),
('minat','Hidroponik','agro_lingkungan','agro',61,1),
('minat','Lingkungan','agro_lingkungan','agro',62,1),
('minat','Agribisnis','agro_lingkungan','agro',63,1),
('minat','Hukum','hukum_pemerintahan','hukum',64,1),
('minat','Debat','hukum_pemerintahan','hukum',65,1),
('minat','Pemerintahan','hukum_pemerintahan','hukum',66,1),
('minat','Advokasi','hukum_pemerintahan','hukum',67,1),
('minat','Kuliner','kuliner_layanan','kuliner',68,1),
('minat','Memasak','kuliner_layanan','kuliner',69,1),
('minat','Bakery','kuliner_layanan','kuliner',70,1),
('minat','Barista','kuliner_layanan','kuliner',71,1),
('minat','Pariwisata','kuliner_layanan','kuliner',72,1),
('minat','Keagamaan','spiritual_keagamaan','agama',73,1),
('minat','Dakwah','spiritual_keagamaan','agama',74,1),
('minat','Moderasi Beragama','spiritual_keagamaan','agama',75,1),
('hobi','Coding','teknologi_software','teknologi',76,1),
('hobi','Ngoding','teknologi_software','teknologi',77,1),
('hobi','Membuat Website','teknologi_software','teknologi',78,1),
('hobi','Membuat Aplikasi','teknologi_software','teknologi',79,1),
('hobi','Oprek Komputer','teknologi_software','teknologi',80,1),
('hobi','Mengolah Data','data_analitik','data',81,1),
('hobi','Membuat Grafik','data_analitik','data',82,1),
('hobi','Bermain Excel','data_analitik','data',83,1),
('hobi','Menganalisis Angka','data_analitik','data',84,1),
('hobi','Menggambar','desain_kreatif','kreatif',85,1),
('hobi','Desain Poster','desain_kreatif','kreatif',86,1),
('hobi','Edit Foto','desain_kreatif','kreatif',87,1),
('hobi','Edit Video','desain_kreatif','kreatif',88,1),
('hobi','Fotografi','desain_kreatif','kreatif',89,1),
('hobi','Membuat Logo','desain_kreatif','kreatif',90,1),
('hobi','Jualan','bisnis_marketing','bisnis',91,1),
('hobi','Promosi Produk','bisnis_marketing','bisnis',92,1),
('hobi','Membuat Konten Jualan','bisnis_marketing','bisnis',93,1),
('hobi','Negosiasi','bisnis_marketing','bisnis',94,1),
('hobi','Mencatat Keuangan','keuangan_administrasi','keuangan',95,1),
('hobi','Mengatur Arsip','keuangan_administrasi','keuangan',96,1),
('hobi','Membuat Rekap','keuangan_administrasi','keuangan',97,1),
('hobi','Mengelola Dokumen','keuangan_administrasi','keuangan',98,1),
('hobi','Eksperimen Sains','kesehatan_sains','kesehatan',99,1),
('hobi','Membaca Kesehatan','kesehatan_sains','kesehatan',100,1),
('hobi','Merawat Orang','kesehatan_sains','kesehatan',101,1),
('hobi','Praktikum','kesehatan_sains','kesehatan',102,1),
('hobi','Mengajar Teman','pendidikan_sosial','sosial',103,1),
('hobi','Berorganisasi','pendidikan_sosial','sosial',104,1),
('hobi','Mendengar Curhat','pendidikan_sosial','sosial',105,1),
('hobi','Kegiatan Sosial','pendidikan_sosial','sosial',106,1),
('hobi','Menulis Cerita','komunikasi_media','komunikasi',107,1),
('hobi','Presentasi','komunikasi_media','komunikasi',108,1),
('hobi','Membuat Podcast','komunikasi_media','komunikasi',109,1),
('hobi','Membuat Caption','komunikasi_media','komunikasi',110,1),
('hobi','Bahasa Asing','komunikasi_media','komunikasi',111,1),
('hobi','Merakit Elektronik','teknik_rekayasa','teknik',112,1),
('hobi','Servis Perangkat','teknik_rekayasa','teknik',113,1),
('hobi','Oprek Motor','teknik_rekayasa','teknik',114,1),
('hobi','Membuat Alat','teknik_rekayasa','teknik',115,1),
('hobi','Berkebun','agro_lingkungan','agro',116,1),
('hobi','Merawat Hewan','agro_lingkungan','agro',117,1),
('hobi','Budidaya Ikan','agro_lingkungan','agro',118,1),
('hobi','Membuat Kompos','agro_lingkungan','agro',119,1),
('hobi','Debat','hukum_pemerintahan','hukum',120,1),
('hobi','Membaca Isu Sosial','hukum_pemerintahan','hukum',121,1),
('hobi','Diskusi Aturan','hukum_pemerintahan','hukum',122,1),
('hobi','Memasak','kuliner_layanan','kuliner',123,1),
('hobi','Membuat Kue','kuliner_layanan','kuliner',124,1),
('hobi','Meracik Minuman','kuliner_layanan','kuliner',125,1),
('hobi','Mengaji','spiritual_keagamaan','agama',126,1),
('hobi','Kajian','spiritual_keagamaan','agama',127,1),
('hobi','Kegiatan Rohani','spiritual_keagamaan','agama',128,1),
('bakat','Logika Pemrograman','teknologi_software','teknologi',129,1),
('bakat','Problem Solving Teknis','teknologi_software','teknologi',130,1),
('bakat','Memahami Alur Sistem','teknologi_software','teknologi',131,1),
('bakat','Debugging','teknologi_software','teknologi',132,1),
('bakat','Analisis Angka','data_analitik','data',133,1),
('bakat','Teliti Membaca Data','data_analitik','data',134,1),
('bakat','Berpikir Statistik','data_analitik','data',135,1),
('bakat','Membuat Kesimpulan Data','data_analitik','data',136,1),
('bakat','Visual Kreatif','desain_kreatif','kreatif',137,1),
('bakat','Komposisi Warna','desain_kreatif','kreatif',138,1),
('bakat','Membuat Layout','desain_kreatif','kreatif',139,1),
('bakat','Storytelling Visual','desain_kreatif','kreatif',140,1),
('bakat','Negosiasi','bisnis_marketing','bisnis',141,1),
('bakat','Melihat Peluang','bisnis_marketing','bisnis',142,1),
('bakat','Strategi Promosi','bisnis_marketing','bisnis',143,1),
('bakat','Kepemimpinan Bisnis','bisnis_marketing','bisnis',144,1),
('bakat','Teliti Mencatat','keuangan_administrasi','keuangan',145,1),
('bakat','Rapi Administrasi','keuangan_administrasi','keuangan',146,1),
('bakat','Menghitung Keuangan','keuangan_administrasi','keuangan',147,1),
('bakat','Membuat Laporan','keuangan_administrasi','keuangan',148,1),
('bakat','Observasi Sains','kesehatan_sains','kesehatan',149,1),
('bakat','Teliti Praktikum','kesehatan_sains','kesehatan',150,1),
('bakat','Memahami Biologi/Kimia','kesehatan_sains','kesehatan',151,1),
('bakat','Empati Pelayanan','kesehatan_sains','kesehatan',152,1),
('bakat','Mengajar','pendidikan_sosial','sosial',153,1),
('bakat','Empati','pendidikan_sosial','sosial',154,1),
('bakat','Memimpin Kelompok','pendidikan_sosial','sosial',155,1),
('bakat','Membimbing Teman','pendidikan_sosial','sosial',156,1),
('bakat','Komunikasi','komunikasi_media','komunikasi',157,1),
('bakat','Public Speaking','komunikasi_media','komunikasi',158,1),
('bakat','Menulis','komunikasi_media','komunikasi',159,1),
('bakat','Bahasa','komunikasi_media','komunikasi',160,1),
('bakat','Membangun Relasi','komunikasi_media','komunikasi',161,1),
('bakat','Troubleshooting','teknik_rekayasa','teknik',162,1),
('bakat','Mekanik','teknik_rekayasa','teknik',163,1),
('bakat','Membaca Rangkaian','teknik_rekayasa','teknik',164,1),
('bakat','Praktik Alat','teknik_rekayasa','teknik',165,1),
('bakat','Observasi Tanaman','agro_lingkungan','agro',166,1),
('bakat','Budidaya','agro_lingkungan','agro',167,1),
('bakat','Merawat Hewan','agro_lingkungan','agro',168,1),
('bakat','Peka Lingkungan','agro_lingkungan','agro',169,1),
('bakat','Argumentasi','hukum_pemerintahan','hukum',170,1),
('bakat','Menganalisis Kasus','hukum_pemerintahan','hukum',171,1),
('bakat','Berpikir Kritis Sosial','hukum_pemerintahan','hukum',172,1),
('bakat','Rasa Kuliner','kuliner_layanan','kuliner',173,1),
('bakat','Kreativitas Resep','kuliner_layanan','kuliner',174,1),
('bakat','Pelayanan Pelanggan','kuliner_layanan','kuliner',175,1),
('bakat','Ceramah','spiritual_keagamaan','agama',176,1),
('bakat','Membaca Kitab','spiritual_keagamaan','agama',177,1),
('bakat','Etika Keagamaan','spiritual_keagamaan','agama',178,1),
('pengalaman','Proyek Website','teknologi_software','teknologi',179,1),
('pengalaman','Membuat Aplikasi','teknologi_software','teknologi',180,1),
('pengalaman','Lomba Coding','teknologi_software','teknologi',181,1),
('pengalaman','Magang IT','teknologi_software','teknologi',182,1),
('pengalaman','Mengelola Server','teknologi_software','teknologi',183,1),
('pengalaman','Olah Data Excel','data_analitik','data',184,1),
('pengalaman','Membuat Dashboard','data_analitik','data',185,1),
('pengalaman','Riset Data','data_analitik','data',186,1),
('pengalaman','Laporan Statistik','data_analitik','data',187,1),
('pengalaman','Desain Logo','desain_kreatif','kreatif',188,1),
('pengalaman','Desain Poster','desain_kreatif','kreatif',189,1),
('pengalaman','Konten Visual','desain_kreatif','kreatif',190,1),
('pengalaman','Dokumentasi Acara','desain_kreatif','kreatif',191,1),
('pengalaman','Video Editing','desain_kreatif','kreatif',192,1),
('pengalaman','Jualan Online','bisnis_marketing','bisnis',193,1),
('pengalaman','Bisnis Kecil','bisnis_marketing','bisnis',194,1),
('pengalaman','Panitia Sponsorship','bisnis_marketing','bisnis',195,1),
('pengalaman','Promosi Produk','bisnis_marketing','bisnis',196,1),
('pengalaman','Marketplace','bisnis_marketing','bisnis',197,1),
('pengalaman','Bendahara','keuangan_administrasi','keuangan',198,1),
('pengalaman','Laporan Kas','keuangan_administrasi','keuangan',199,1),
('pengalaman','Admin Organisasi','keuangan_administrasi','keuangan',200,1),
('pengalaman','Rekap Data','keuangan_administrasi','keuangan',201,1),
('pengalaman','Input Transaksi','keuangan_administrasi','keuangan',202,1),
('pengalaman','Praktikum Biologi','kesehatan_sains','kesehatan',203,1),
('pengalaman','Praktikum Kimia','kesehatan_sains','kesehatan',204,1),
('pengalaman','PMR','kesehatan_sains','kesehatan',205,1),
('pengalaman','Kegiatan Kesehatan','kesehatan_sains','kesehatan',206,1),
('pengalaman','Asisten Lab','kesehatan_sains','kesehatan',207,1),
('pengalaman','Mengajar Les','pendidikan_sosial','sosial',208,1),
('pengalaman','Mentor Teman','pendidikan_sosial','sosial',209,1),
('pengalaman','Ketua Organisasi','pendidikan_sosial','sosial',210,1),
('pengalaman','Relawan','pendidikan_sosial','sosial',211,1),
('pengalaman','Konseling Teman','pendidikan_sosial','sosial',212,1),
('pengalaman','MC','komunikasi_media','komunikasi',213,1),
('pengalaman','Moderator','komunikasi_media','komunikasi',214,1),
('pengalaman','Jurnalistik Sekolah','komunikasi_media','komunikasi',215,1),
('pengalaman','Membuat Artikel','komunikasi_media','komunikasi',216,1),
('pengalaman','Konten Media Sosial','komunikasi_media','komunikasi',217,1),
('pengalaman','Servis Komputer','teknik_rekayasa','teknik',218,1),
('pengalaman','Instalasi Jaringan','teknik_rekayasa','teknik',219,1),
('pengalaman','Proyek IoT','teknik_rekayasa','teknik',220,1),
('pengalaman','Praktik Bengkel','teknik_rekayasa','teknik',221,1),
('pengalaman','Troubleshooting Alat','teknik_rekayasa','teknik',222,1),
('pengalaman','Budidaya Tanaman','agro_lingkungan','agro',223,1),
('pengalaman','Budidaya Ikan','agro_lingkungan','agro',224,1),
('pengalaman','Proyek Hidroponik','agro_lingkungan','agro',225,1),
('pengalaman','Kebun Sekolah','agro_lingkungan','agro',226,1),
('pengalaman','Pengolahan Kompos','agro_lingkungan','agro',227,1),
('pengalaman','Lomba Debat','hukum_pemerintahan','hukum',228,1),
('pengalaman','OSIS Bidang Advokasi','hukum_pemerintahan','hukum',229,1),
('pengalaman','Diskusi Hukum','hukum_pemerintahan','hukum',230,1),
('pengalaman','Simulasi Sidang','hukum_pemerintahan','hukum',231,1),
('pengalaman','Jualan Makanan','kuliner_layanan','kuliner',232,1),
('pengalaman','Praktik Boga','kuliner_layanan','kuliner',233,1),
('pengalaman','Pre-order Makanan','kuliner_layanan','kuliner',234,1),
('pengalaman','Katering Kecil','kuliner_layanan','kuliner',235,1),
('pengalaman','Remaja Masjid','spiritual_keagamaan','agama',236,1),
('pengalaman','Kegiatan Rohani','spiritual_keagamaan','agama',237,1),
('pengalaman','Lomba Dakwah','spiritual_keagamaan','agama',238,1),
('pengalaman','Mengajar Mengaji','spiritual_keagamaan','agama',239,1),
('prestasi','Juara Coding','teknologi_software','teknologi',240,1),
('prestasi','Sertifikat Web Developer','teknologi_software','teknologi',241,1),
('prestasi','Finalis Hackathon','teknologi_software','teknologi',242,1),
('prestasi','Juara Statistik','data_analitik','data',243,1),
('prestasi','Sertifikat Data Analyst','data_analitik','data',244,1),
('prestasi','Lomba Karya Ilmiah Data','data_analitik','data',245,1),
('prestasi','Juara Desain','desain_kreatif','kreatif',246,1),
('prestasi','Sertifikat Desain Grafis','desain_kreatif','kreatif',247,1),
('prestasi','Finalis Video Kreatif','desain_kreatif','kreatif',248,1),
('prestasi','Juara Business Plan','bisnis_marketing','bisnis',249,1),
('prestasi','Sertifikat Digital Marketing','bisnis_marketing','bisnis',250,1),
('prestasi','Lomba Kewirausahaan','bisnis_marketing','bisnis',251,1),
('prestasi','Juara Akuntansi','keuangan_administrasi','keuangan',252,1),
('prestasi','Sertifikat Administrasi','keuangan_administrasi','keuangan',253,1),
('prestasi','Bendahara Terbaik','keuangan_administrasi','keuangan',254,1),
('prestasi','Juara Biologi','kesehatan_sains','kesehatan',255,1),
('prestasi','Juara Kimia','kesehatan_sains','kesehatan',256,1),
('prestasi','Sertifikat PMR','kesehatan_sains','kesehatan',257,1),
('prestasi','Lomba Kesehatan','kesehatan_sains','kesehatan',258,1),
('prestasi','Duta Pelajar','pendidikan_sosial','sosial',259,1),
('prestasi','Ketua Organisasi','pendidikan_sosial','sosial',260,1),
('prestasi','Sertifikat Tutor','pendidikan_sosial','sosial',261,1),
('prestasi','Relawan Pendidikan','pendidikan_sosial','sosial',262,1),
('prestasi','Juara Pidato','komunikasi_media','komunikasi',263,1),
('prestasi','Juara Menulis','komunikasi_media','komunikasi',264,1),
('prestasi','Jurnalistik','komunikasi_media','komunikasi',265,1),
('prestasi','Public Speaking','komunikasi_media','komunikasi',266,1),
('prestasi','Juara Robotik','teknik_rekayasa','teknik',267,1),
('prestasi','Sertifikat Jaringan','teknik_rekayasa','teknik',268,1),
('prestasi','Lomba Otomotif','teknik_rekayasa','teknik',269,1),
('prestasi','Lomba Elektronika','teknik_rekayasa','teknik',270,1),
('prestasi','Juara Hidroponik','agro_lingkungan','agro',271,1),
('prestasi','Lomba Pertanian','agro_lingkungan','agro',272,1),
('prestasi','Proyek Lingkungan','agro_lingkungan','agro',273,1),
('prestasi','Budidaya Ikan','agro_lingkungan','agro',274,1),
('prestasi','Juara Debat','hukum_pemerintahan','hukum',275,1),
('prestasi','Lomba Hukum','hukum_pemerintahan','hukum',276,1),
('prestasi','Simulasi Sidang','hukum_pemerintahan','hukum',277,1),
('prestasi','Juara Memasak','kuliner_layanan','kuliner',278,1),
('prestasi','Sertifikat Boga','kuliner_layanan','kuliner',279,1),
('prestasi','Lomba Barista','kuliner_layanan','kuliner',280,1),
('prestasi','Juara Dakwah','spiritual_keagamaan','agama',281,1),
('prestasi','Lomba MTQ','spiritual_keagamaan','agama',282,1),
('prestasi','Sertifikat Keagamaan','spiritual_keagamaan','agama',283,1)
ON DUPLICATE KEY UPDATE
  mapped_key = VALUES(mapped_key),
  kategori_hint = VALUES(kategori_hint),
  sort_order = VALUES(sort_order),
  is_active = VALUES(is_active);
